### ISSUE TITLE
Program will not log out unless application has loaded the VPN Node list.

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/NicelandVPN#1]
### Issue
When logging out of the program, it will get stuck logging out before the VPN list loads.

### Secondary issue from the primary issue
Application will not respond to other menu clicks unless you load the Nodes list.

### Information
Version: [v2.0.2](https://github.com/tunnels-is/NicelandVPN/tree/v2.0.2)
Windows 11 x64 Enterprise (Version 10.0.22000.1936)

### Video

https://github.com/tunnels-is/NicelandVPN/assets/19499442/bae14938-dba0-4dc3-bb1f-41ab5ac9d89b

**Comment by zveinn** [comment]
logging out should not have such a long timeout for the loader. We've fixed the logout method itself and added a 5 second timeout for the loader screen.
