### ISSUE TITLE
[request] DNS Statistics 

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/NicelandVPN#2]
# Feature Request

Would like the ability to see how many times a SLD or SUB.SLD were blocked over time. 

For example, maybe a like a stat window that shows SLD Count Filter List
maybe in the format of

### SLD Block Counter
| SLD | COUNT | filter list |
| ---- | --- | ----- | 
| microsoft.com | 34 | TELEMETRY |
| google.com | 31 | TELEMETRY |
| THEONION.com | 11 | FAKENEWS |

### URL Block Count
| SUB | SLD | COUNT | filter list |
| ---- | --- | ----- |  -------|
| im_stealing_your_data | microsoft.com | 98 | TELEMETRY |
| im_stealing_your_data2 | microsoft.com | 78 | TELEMETRY |
| im_stealing_your_data3 | microsoft.com | 74 | TELEMETRY |
| moredata.im_stealing_your_data2 | microsoft.com | 34 | TELEMETRY |

have something that also limits it to where the user has like how many times a SLD was blocked or show the top 10 sites blocked.

**Comment by zveinn** [comment]
Will be added on next release
